# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lnzimand <lnzimand@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/16 09:37:33 by lnzimand          #+#    #+#              #
#    Updated: 2019/09/16 09:54:57 by lnzimand         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FLAGS = -Wall -Werror -Wextra -c

SRC = get_next_line.c

OBJ = get_next_line.o

all:
	gcc $(FLAGS) $(SRC)

clean:
	rm -f $(OBJ)

.PHONY: all, clean
